In [ ]:
"""
날짜 : 2021/10/18
이름 : 남언우
내용 : 파이썬 Numpy 패키지 실습하기
Numpy 라이브러리
 - 고성능의 수치계산을 위한 파이썬 라이브러리
 - 파이썬의 기본 리스트 보다 월등한 연산 성능
 - 행렬이나 대규모 다차원 배열 처리를 지원
"""
import numpy as np


In [ ]:
# numpy 벡터
v1 = np.array([1,2,3,4,5])
print('v1:',v1)

v2 = np.arange(5)
print('v2:',v2)

v1: [1 2 3 4 5]
v2: [0 1 2 3 4]


In [ ]:
# 0 ~ 1 사이의 임의의 실수 100개
result1 = np.random.rand(100)
# 표준정규분포를 따르는 실수 100개
result2 = np.random.randn(100)
# 0 ~ 9 사이의 임의의 정수
result3 = np.random.randint(10)
result1,result2,result3

(array([0.35762276, 0.58152754, 0.71453337, 0.69697543, 0.03042261,
        0.01130843, 0.70057675, 0.05100042, 0.44827057, 0.2047244 ,
        0.05007147, 0.68460801, 0.8234386 , 0.86388971, 0.18911786,
        0.35530996, 0.16682248, 0.57401775, 0.48477766, 0.92099873,
        0.24109609, 0.96678769, 0.88913129, 0.17096055, 0.00726962,
        0.57377727, 0.78936823, 0.36316943, 0.85590881, 0.03531723,
        0.40810086, 0.70663108, 0.63034075, 0.22816267, 0.13005248,
        0.66651894, 0.56354306, 0.95181392, 0.37427392, 0.98629748,
        0.57026743, 0.59909944, 0.01402349, 0.28268057, 0.00129899,
        0.75980682, 0.53283075, 0.05660788, 0.351175  , 0.32860293,
        0.25734984, 0.33289166, 0.29210625, 0.1730058 , 0.27504827,
        0.46616874, 0.43985733, 0.78856923, 0.19586639, 0.82741132,
        0.84071201, 0.99523197, 0.73808468, 0.36515977, 0.84592081,
        0.32754389, 0.69883896, 0.22402082, 0.07307562, 0.22821892,
        0.5004465 , 0.88893324, 0.61916965, 0.52

In [ ]:
# numpy 행렬
m1 = np.array([[1,2], [3,4]])
print(m1)

m2 = np.array([[1,2,3],[4,5,6],[6,7,8]])
print(m2)

m3 = np.ones([2,4])
print(m3)

m4 = np.zeros([3,2])
print(m4)


[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [6 7 8]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# 행렬 인덱싱
mat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(mat)

print(mat[0,0])
print(mat[0,:])
print(mat[:,0])

print(mat[0:2,0:2])
print(mat[:,0:2])
print(mat[:,2:4])
print(mat[1:3,1:3])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[1 2 3 4]
[1 5 9]
[[1 2]
 [5 6]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]
